name: geoflutterfire_example
description: Demonstrates how to use the geoflutterfire plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geo_fire:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

  cloud_firestore: ^4.0.2
  google_maps_flutter: ^2.2.1
