name: geo_fire
description: GeoFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 0.0.1
homepage: https://github.com/cedvdb/geofire_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.2
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
